name: Refresh GitHub Badge Cache

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  refresh-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update badge URL with timestamp
        run: |
          TIMESTAMP=$(date +%s)
          sed -i 's|\(https://user-badge\.committers\.top/sri_lanka_public/nirmal-404\.svg\)[^)]*|\1?v='"$TIMESTAMP"'|g' README.md

      - name: Commit and push changes using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/nirmal-404/nirmal-404.git
          git add README.md
          git commit -m "chore: refresh badge cache"
          git push origin main
